import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div lang="en" id ="container">
      <div className="flex flex-col min-h-screen bg-gray-200">
        {/* header */}
        <header>
        <div>
            <div className="h-18 bg-gray-800 flex flex-wrap items-center justify-between mx-auto p-6">
                <Link href={"/"} className="text-5xl text-white font-semibold">
                    Home
                </Link>

                <div className="text-xl">
                    Menu
                </div>
            </div>
        </div>
        </header>

        {/* main body */}
        <main>
          <body className={inter.className}>{children}</body>
        </main>

        {/* footer */}
        <footer className="h-16 bg-gray-800 text-white flex items-center justify-center">
          <div className='extra'>
           ©copyright developed by Zhang, Haoyuan, 2023
          </div>
        </footer>
      </div>
    </div>
  )
}
