import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/nav-bar.jsx"
import FootBar from './components/foot-bar.jsx'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" id="container">
      <body className={inter.className}>
        <div className="flex flex-col h-screen bg-gray-200">
          <header>
            <NavBar/>
          </header>
          <main>
            {children}
          </main>
          <footer>
            <FootBar/>
          </footer>
        </div>
      </body>
    </html>
  );
}
