import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './Components/nav-bar.jsx'
import FootBar from './Components/foot-bar.jsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div lang="en" id ="container">
      <div className="flex flex-col min-h-screen bg-gray-200">
        {/* header */}
        <header>
          <NavBar/>
        </header>

        {/* main body */}
        <main>
          <body className={inter.className}>{children}</body>
        </main>

        {/* footer */}
        <FootBar/>
      </div>
    </div>
  )
}
